### PR TITLE
Fix TestServerAction for methods parameters

### PR DESCRIPTION
**Pull request by serweck**
This fix when you send a method like Guid.NewGuid() and execute this.

`            return await Fixture.Server
                .CreateHttpApiRequest<CommentsController>(r => r.GetComment(Guid.NewGuid(), id), new { version = 1 })
                        .WithIdentity(IdentitiesGenerator.Administrator, TestServerDefaults.AuthenticationScheme)
                        .GetAsync();
`

### CODE REVIEW

**Comment by Sergio1192** [comment]
Hello @serweck,
We need some tests to check for new features or bugs fixes.

**Comment by serweck** [comment]
ok, i will do :)

**Comment by Sergio1192** [comment]
> ok, i will do :)

Thank a lot to contribute :)

I think, you have closed the PR wrongly.

**Comment by serweck** [comment]
yes sorry, i'm new using github with forks. I do other PR

**Pull request closed without merging**
